---

- name: create download directory
  file: path=/tmp/gitbucket/{{ git_bucket_version }} state=directory

- name: download war file
  uri:  url=https://github.com/takezoe/gitbucket/releases/download/{{ git_bucket_version }}/gitbucket.war
        dest=/tmp/gitbucket/{{ git_bucket_version }}/gitbucket.war

- name: stop jetty
  service: name=jetty state=stopped
  notify: restart jetty

- name: remove current war file
  file: path={{ jetty_home }}/webapps/{{ application_name }}.war state=absent

- name: deploy war file
  command: cp /tmp/gitbucket/{{ git_bucket_version }}/gitbucket.war {{ jetty_home }}/webapps/{{ application_name }}.war
